title: "Can Mutlu"
email: "cmutlu@g.harvard.edu"
description: >-
     

url: "https://canemirmutlu.github.io"
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-feed

nav:
  - name: "Research"
    link: /research
  - name: "CV"
    link: /cv/cv_conevska.pdf
  - name: "Teaching"
    #link: /teaching
